### ISSUE TITLE
No complete option on campaigns

### ISSUE THREAD

**Issue by ProfDoof** [gophish/python-api-documentation#2]
There is no `complete` method mentioned in the documentation for the `campaigns` part of the api client. Based off the code [here](https://github.com/gophish/api-client-python/blob/b91511257dee32bfe04accee9b7975ffd8412943/gophish/api/campaigns.py#L32-L36) it exists.

**Comment by jordan-wright** [comment]
Great catch! I've fixed this in b4f974056e61ccbfd89e5287b61abc0f32d4a12b.
